using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using VOL.Core.DBManager;
using VOL.Core.Extensions;
using VOL.Core.Infrastructure;
using VOL.Entity.DomainModels;

namespace VOL.Core.Utilities
{
    /// <summary>
    /// Provides helper methods for Excel operations using the EPPlus library.
    /// This includes importing data from Excel files into lists of objects or DataTables,
    /// and exporting data from lists of objects or DataTables to Excel files.
    /// It also supports generating Excel templates with predefined headers and dropdowns for dictionary-bound fields.
    /// </summary>
    public class EPPlusHelper
    {
        /// <summary>
        /// Imports data from an Excel file to a list of objects of type T.
        /// This method is typically used with Excel templates generated by the framework,
        /// validating data against expected column names, required fields, and dictionary values.
        /// </summary>
        /// <typeparam name="T">The type of objects to import. Must be a class with a parameterless constructor.</typeparam>
        /// <param name="path">The full path to the Excel file.</param>
        /// <param name="exportColumns">Optional. An expression to specify which entity properties (columns) to include in the import.
        /// If provided, only these columns will be processed. Example: `x => new { x.Name, x.Code }`.</param>
        /// <param name="ignoreTemplate">Optional. A list of entity property names to ignore during import.
        /// This is not used if <paramref name="exportColumns"/> is specified.</param>
        /// <param name="readValue">Optional. A custom function to read or transform cell values during import.
        /// Parameters: current cell value (string), worksheet, cell range, row index, column index. Returns transformed string value.</param>
        /// <param name="ignoreSelectValidationColumns">Optional. An expression to specify entity properties for which
        /// dictionary-based dropdown/select list validation should be ignored. Example: `x => new { x.Category }`.</param>
        /// <returns>A <see cref="WebResponseContent"/> object. If successful, <see cref="WebResponseContent.Data"/> contains the list of imported entities.
        /// If an error occurs, <see cref="WebResponseContent.Message"/> contains the error details.</returns>
        public static WebResponseContent ReadToDataTable<T>(string path,
            Expression<Func<T, object>> exportColumns = null,
            List<string> ignoreTemplate = null,
            Func<string, ExcelWorksheet, ExcelRange, int, int, string> readValue = null,
            Expression<Func<T, object>> ignoreSelectValidationColumns = null
            ) where T : class // Added class constraint for Activator.CreateInstance<T>()
        {
            WebResponseContent responseContent = new WebResponseContent();

            FileInfo file = new FileInfo(path);
            if (!file.Exists) return responseContent.Error("未找到上传的文件,请重新上传");

            List<T> entities = new List<T>();
            // The 'using' statement ensures that the ExcelPackage object is properly disposed of,
            // releasing any resources it holds (like file handles or memory streams).
            using (ExcelPackage package = new ExcelPackage(file))
            {
                // Check if the workbook has any worksheets and if the first worksheet has more than one row (header row)
                if (package.Workbook.Worksheets.Count == 0 ||
                    package.Workbook.Worksheets.FirstOrDefault().Dimension == null || // Ensure Dimension is not null
                    package.Workbook.Worksheets.FirstOrDefault().Dimension.End.Row <= 1)
                    return responseContent.Error("未导入数据或Excel文件内容为空");

                // Get column configuration (CN name, DB name, required status, etc.) for the entity type T
                List<CellOptions> cellOptions = GetExportColumnInfo(typeof(T).Name, false, false, columns: exportColumns?.GetExpressionToArray());

                // Filter cellOptions based on exportColumns or ignoreTemplate
                if (exportColumns != null)
                {
                    cellOptions = cellOptions
                        .Where(x => exportColumns.GetExpressionToArray().Select(s => s.ToLower()).Contains(x.ColumnName.ToLower()))
                        .ToList();
                }
                else if (ignoreTemplate != null)
                {
                    cellOptions = cellOptions
                        .Where(x => !ignoreTemplate.Select(s => s.ToLower()).Contains(x.ColumnName.ToLower()))
                        .ToList();
                }

                ExcelWorksheet sheetFirst = package.Workbook.Worksheets.FirstOrDefault();

                // Validate header row in the Excel sheet against the expected columns from cellOptions
                for (int j = sheetFirst.Dimension.Start.Column, k = sheetFirst.Dimension.End.Column; j <= k; j++)
                {
                    string columnCNName = sheetFirst.Cells[1, j].Value?.ToString()?.Trim();
                    if (!string.IsNullOrEmpty(columnCNName))
                    {
                        CellOptions options = cellOptions.FirstOrDefault(x => x.ColumnCNName == columnCNName);
                        if (options == null)
                        {
                            // If a column in Excel is not found in our template configuration
                            return responseContent.Error("导入文件列[" + columnCNName + "]不是模板中的列");
                        }
                        if (options.Index > 0) // Check for duplicate column names in the Excel header
                        {
                            return responseContent.Error("导入文件列[" + columnCNName + "]不能重复");
                        }
                        options.Index = j; // Store the actual column index from the Excel file
                    }
                }
                // Check if all required columns (as per template) are present in the Excel file
                if (cellOptions.Exists(x => x.Index == 0 && x.Requierd))
                {
                    return responseContent.Error("导入文件列必须与导入模板相同, 缺少必填列: " + cellOptions.FirstOrDefault(x => x.Index == 0 && x.Requierd)?.ColumnCNName);
                }

                // Get property names for which dictionary validation should be skipped
                string[] ignoreSelectValidationFields = ignoreSelectValidationColumns?.GetExpressionToArray() ?? new string[0];

                // Get PropertyInfo objects for type T that correspond to the columns we are processing
                PropertyInfo[] propertyInfos = typeof(T).GetProperties()
                       .Where(x => cellOptions.Select(s => s.ColumnName).Contains(x.Name))
                       .ToArray();

                ExcelWorksheet sheet = package.Workbook.Worksheets.FirstOrDefault(); // Re-accessing, should be same as sheetFirst
                // Iterate through data rows (starting from the second row, as first is header)
                for (int m = sheet.Dimension.Start.Row + 1, n = sheet.Dimension.End.Row; m <= n; m++)
                {
                    T entity = Activator.CreateInstance<T>(); // Create a new instance of T for each row
                    // Iterate through columns based on Excel file's dimensions
                    for (int j = sheet.Dimension.Start.Column, k = sheet.Dimension.End.Column; j <= k; j++)
                    {
                        string value = sheet.Cells[m, j].Value?.ToString();
                        // Apply custom value transformation if provided
                        if (readValue != null)
                        {
                            value = readValue(value, sheet, sheet.Cells[m, j], m, j);
                        }

                        // Find the CellOptions corresponding to the current Excel column index
                        CellOptions options = cellOptions.FirstOrDefault(x => x.Index == j);
                        if (options == null) continue; // Skip columns not in our cellOptions mapping (e.g., extra columns in Excel)

                        PropertyInfo property = propertyInfos.FirstOrDefault(x => x.Name == options.ColumnName);
                        if (property == null) continue; // Skip if no corresponding property in T (should not happen if cellOptions is derived from T)

                        // Validate required fields
                        if (string.IsNullOrEmpty(value))
                        {
                            if (options.Requierd)
                            {
                                return responseContent.Error($"第{m}行[{options.ColumnCNName}]验证未通过,不能为空。");
                            }
                            continue; // Skip if value is empty and not required
                        }

                        // Validate against dictionary data source if applicable
                        if (!string.IsNullOrEmpty(options.DropNo) && !ignoreSelectValidationFields.Contains(property.Name))
                        {
                            if (options.KeyValues == null) // KeyValues should be populated by GetExportColumnInfo
                            {
                                return responseContent.Error($"[{options.ColumnCNName}]字段数字典编号[{options.DropNo}]缺失或加载失败,请检查字典配置");
                            }
                            string key = null; // This will store the dictionary key corresponding to the Excel value
                            // Handle multi-select (comma-separated values) for selectList or checkbox
                            if ((options.EditType == "selectList" || options.EditType == "checkbox") && !string.IsNullOrEmpty(value))
                            {
                                var cellValues = value.Replace("，", ",").Split(",").Where(x => !string.IsNullOrEmpty(x)).Select(s=>s.Trim()).ToArray();
                                var keys = options.KeyValues.Where(x => cellValues.Contains(x.Value)) // Match Excel display values to dictionary display values
                                    .Select(s => s.Key).ToArray();
                                if (cellValues.Length == keys.Length) key = string.Join(",", keys); // All values found, join corresponding keys
                            }
                            else // Handle single-select
                            {
                                key = options.KeyValues.FirstOrDefault(x => x.Value == value.Trim()).Key;
                            }

                            if (key == null) // If no matching key found in dictionary
                            {
                                string validValuesHint = options.KeyValues.Count < 20 ? (string.Join(',', options.KeyValues.Select(s => s.Value))) : $"有效值之一({options.ColumnCNName})";
                                return responseContent.Error($"第{m}行[{options.ColumnCNName}]验证未通过,必须是字典数据中[{validValuesHint}]的值。当前值: '{value}'");
                            }
                            value = key; // Use the dictionary key as the actual value to be set on the entity
                        }
                        // Handle DateTime conversion, especially for Excel's numeric date format
                        else if (property.PropertyType == typeof(DateTime) || property.PropertyType == typeof(DateTime?))
                        {
                            if (double.TryParse(value, out double dValue) && value.Length == 5 && dValue > 10000 && dValue < 60000) // Heuristic for OADate
                            {
                                try { property.SetValue(entity, DateTime.FromOADate(dValue)); }
                                catch { property.SetValue(entity, value.ChangeType(property.PropertyType)); } // Fallback to standard conversion
                            }
                            else
                            {
                                property.SetValue(entity, value.ChangeType(property.PropertyType));
                            }
                            continue; // Value already set
                        }

                        // General property validation (e.g., data type, length)
                        (bool isValid, string errorMsg, object convertedValue) result = property.ValidationProperty(value, options.Requierd);
                        if (!isValid)
                        {
                            return responseContent.Error($"第{m}行[{options.ColumnCNName}]验证未通过,{errorMsg}");
                        }
                        // Set property value (ChangeType handles basic conversions like string to int, bool, etc.)
                        property.SetValue(entity, value.ChangeType(property.PropertyType));
                    }
                    entity.SetCreateDefaultVal(); // Apply any default creation values defined on the entity
                    entities.Add(entity);
                }
            }
            return responseContent.OK(null, entities); // Return success with the list of imported entities
        }

        /// <summary>
        /// Exports a DataTable to an Excel file using EPPlus.
        /// Column headers are taken from the DataTable's column names or <see cref="CellOptions"/> if provided.
        /// </summary>
        /// <param name="table">The DataTable to export.</param>
        /// <param name="cellOptions">A list of <see cref="CellOptions"/> defining column properties like display name (ColumnCNName), width, and data source for dropdowns (used for mapping values).</param>
        /// <param name="savePath">The directory path where the Excel file will be saved. It will be created if it doesn't exist.</param>
        /// <param name="fileName">The name of the Excel file (e.g., "ExportedData.xlsx").</param>
        /// <returns>The full path to the saved Excel file.</returns>
        /// <exception cref="Exception">Throws exceptions if errors occur during Excel generation or saving (e.g., I/O errors, issues with EPPlus).</exception>
        public static string Export(DataTable table, List<CellOptions> cellOptions, string savePath, string fileName)
        {
            if (!Directory.Exists(savePath)) Directory.CreateDirectory(savePath);

            // Pre-fetch dictionary key-value pairs for columns that have them
            var dicNoKeys = cellOptions
                 .Where(x => !string.IsNullOrEmpty(x.DropNo) && x.KeyValues != null && x.KeyValues.Any())
                 .Select(x => new { x.DropNo, x.ColumnName }).Distinct().ToList();
            try
            {
                // The 'using' statement ensures ExcelPackage is disposed, releasing file locks and resources.
                using (ExcelPackage package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("sheet1"); // Add a new worksheet
                    // Populate header row
                    for (int i = 0; i < table.Columns.Count; i++)
                    {
                        // Style the header cells
                        // The using statement for ExcelRange here is generally not necessary as ExcelRange itself is not IDisposable.
                        using (ExcelRange range = worksheet.Cells[1, i + 1])
                        {
                            range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                            range.Style.Fill.BackgroundColor.SetColor(Color.Gray);
                            range.Style.Font.Color.SetColor(Color.White);
                        }
                        // Get column options (display name, width)
                        CellOptions options = cellOptions.FirstOrDefault(x => x.ColumnName == table.Columns[i].ColumnName);
                        if (options != null)
                        {
                            worksheet.Column(i + 1).Width = options.ColumnWidth / 6.00; // Adjust width (magic number 6.00 likely for pixel conversion)
                            worksheet.Cells[1, i + 1].Value = options.ColumnCNName; // Use display name from options
                        }
                        else
                        {
                            worksheet.Column(i + 1).Width = 15; // Default width if no options found
                            worksheet.Cells[1, i + 1].Value = table.Columns[i].ColumnName; // Use DataTable column name
                        }
                    }

                    // Populate data rows
                    for (int i = 0; i < table.Rows.Count; i++) // Iterate through DataTable rows
                    {
                        for (int j = 0; j < table.Columns.Count; j++) // Iterate through DataTable columns
                        {
                            string cellValue = (table.Rows[i][j] ?? "").ToString(); // Get cell value, default to empty string if null
                            // If column is dictionary-bound, try to convert key to display value
                            if (dicNoKeys.Exists(x => x.ColumnName == table.Columns[j].ColumnName))
                            {
                                string result = null;
                                cellOptions.FirstOrDefault(x => x.ColumnName == table.Columns[j].ColumnName)
                                    ?.KeyValues?.TryGetValue(cellValue, out result); // Look up display value
                                cellValue = result ?? cellValue; // Use display value if found, otherwise original key
                            }
                            worksheet.Cells[i + 2, j + 1].Value = cellValue; // Set cell value in Excel (data starts at row 2)
                        }
                    }
                    // Save the Excel file. This operation can throw I/O exceptions.
                    package.SaveAs(new FileInfo(Path.Combine(savePath, fileName)));
                }
                return Path.Combine(savePath, fileName); // Return the full path to the saved file
            }
            catch (Exception ex)
            {
                VOL.Core.Services.Logger.Error(VOL.Core.Enums.LogLevel.Error, VOL.Core.Enums.LogEvent.Exception, $"Error exporting DataTable to Excel file {fileName}", null, ex);
                throw; // Re-throw to allow the service layer to handle and potentially return a user-friendly error.
            }
        }

        /// <summary>
        /// Exports a list of objects of type T to an Excel file. Can also be used to generate an Excel template
        /// with headers and dropdowns for dictionary-bound fields.
        /// </summary>
        /// <typeparam name="T">The type of objects in the list.</typeparam>
        /// <param name="list">The list of objects to export. If null or empty and <paramref name="template"/> is true,
        /// an empty template with headers (and data validations for dictionaries) is generated.</param>
        /// <param name="exportColumns">Optional. A collection of entity property names to include in the export.
        /// If null, behavior depends on <paramref name="ignoreColumns"/> and default settings from <see cref="CellOptions"/>.</param>
        /// <param name="ignoreColumns">Optional. A collection of entity property names to exclude from the export.
        /// This is not used if <paramref name="exportColumns"/> is specified.</param>
        /// <param name="savePath">The directory path where the Excel file will be saved. It will be created if it doesn't exist.</param>
        /// <param name="fileName">The name of the Excel file (e.g., "ExportedEntities.xlsx").</param>
        /// <param name="template">If true, generates an Excel template. Headers are included, and for fields linked to dictionaries,
        /// data validation dropdowns are created in the Excel sheet. If false, exports data from the <paramref name="list"/>.</param>
        /// <returns>The full path to the saved Excel file.</returns>
        /// <exception cref="Exception">Throws exceptions if errors occur during Excel generation or saving.</exception>
        public static string Export<T>(List<T> list, IEnumerable<string> exportColumns, IEnumerable<string> ignoreColumns, string savePath, string fileName, bool template = false) where T : class
        {
            if (!Directory.Exists(savePath)) Directory.CreateDirectory(savePath);

            // Get column configuration for the entity type T
            List<CellOptions> cellOptions = GetExportColumnInfo(typeof(T).Name, template, columns: exportColumns?.ToArray());
            string fullPath = Path.Combine(savePath, fileName);

            // Identify columns that are dictionary-bound for special handling (display value conversion, template dropdowns)
            var dicNoKeys = cellOptions
                 .Where(x => !string.IsNullOrEmpty(x.DropNo) && x.KeyValues != null && x.KeyValues.Any())
                 .Select(x => new { x.DropNo, x.ColumnName, x.SearchType, x.EditType }).Distinct().ToList();
            // Identify columns that are multi-select (checkbox or selectList) from dictionaries
            var selectListCols = dicNoKeys.Where(x => x.SearchType == "checkbox" || x.SearchType == "selectList" || x.EditType == "checkbox" || x.EditType == "selectList")
                  .Select(s => s.ColumnName).ToArray();

            List<PropertyInfo> propertyInfo; // List of properties to be included in the export

            // Determine which properties to include based on exportColumns or ignoreColumns
            if (exportColumns != null && exportColumns.Any())
            {
                propertyInfo = new List<PropertyInfo>();
                var properties = typeof(T).GetProperties();
                foreach (var name in exportColumns) // Explicitly include specified columns
                {
                    var property = properties.FirstOrDefault(x => x.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
                    if (property != null) propertyInfo.Add(property);
                }
            }
            else if (ignoreColumns != null && ignoreColumns.Any())
            {
                var lowerIgnoreColumns = ignoreColumns.Select(g => g.ToLower()).ToList();
                propertyInfo = typeof(T).GetProperties() // Include properties not in ignoreColumns and present in cellOptions
                  .Where(x => !lowerIgnoreColumns.Contains(x.Name.ToLower()) && cellOptions.Any(s => s.ColumnName == x.Name))
                  .ToList();
            }
            else // Default: use all properties defined in cellOptions
            {
                propertyInfo = new List<PropertyInfo>();
                var properties = typeof(T).GetProperties();
                foreach (var item in cellOptions)
                {
                    var property = properties.FirstOrDefault(x => x.Name == item.ColumnName);
                    if (property != null) propertyInfo.Add(property);
                }
            }

            // Identify date properties for special formatting if not generating a template
            string[] dateArr = null;
            if (!template && list != null)
            {
                dateArr = propertyInfo.Where(x => x.PropertyType == typeof(DateTime) || x.PropertyType == typeof(DateTime?))
                                  .Select(s => s.Name).ToArray();
            }
            try
            {
                using (ExcelPackage package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("sheet1");
                    // Populate header row
                    for (int i = 0; i < propertyInfo.Count; i++)
                    {
                        string columnName = propertyInfo[i].Name;
                        worksheet.Cells[1, i + 1].Style.Fill.PatternType = ExcelFillStyle.Solid;
                        Color backgroundColor = Color.Gray; Color fontColor = Color.White;
                        // Different styling for template headers (especially required fields)
                        if (template)
                        {
                            fontColor = Color.Black;
                            if (cellOptions.Exists(x => x.ColumnName == columnName && x.Requierd)) backgroundColor = Color.Yellow; // Highlight required
                            else backgroundColor = Color.White;
                        }
                        worksheet.Cells[1, i + 1].Style.Fill.BackgroundColor.SetColor(backgroundColor);
                        worksheet.Cells[1, i + 1].Style.Font.Color.SetColor(fontColor);

                        CellOptions options = cellOptions.FirstOrDefault(x => x.ColumnName == columnName);
                        if (options != null)
                        {
                            worksheet.Column(i + 1).Width = options.ColumnWidth / 6.00;
                            worksheet.Cells[1, i + 1].Value = options.ColumnCNName;

                            // If generating a template and column has dictionary values, create a dropdown list
                            if (template && options.KeyValues != null && options.KeyValues.Any())
                            {
                                var validation = worksheet.DataValidations.AddListValidation(worksheet.Cells[2, i + 1, ExcelPackage.MaxRows, i + 1].Address);
                                foreach (var kvp in options.KeyValues)
                                {
                                    validation.Formula.Values.Add(kvp.Value); // Add display values to dropdown
                                }
                            }
                        }
                        else // Fallback if no specific CellOptions found (should ideally not happen if properties are filtered by cellOptions)
                        {
                            columnName = propertyInfo[i].GetTypeCustomValue<DisplayAttribute>(x => x.Name) ?? columnName; // Try to get DisplayAttribute Name
                            worksheet.Column(i + 1).Width = 15;
                            worksheet.Cells[1, i + 1].Value = columnName;
                        }
                    }

                    if (template) // If only template is needed, save and return.
                    {
                        package.SaveAs(new FileInfo(fullPath));
                        return fullPath;
                    }

                    if (list == null) list = new List<T>(); // Ensure list is not null for data export

                    // Helper function to get display values for comma-separated keys (multi-select)
                    IEnumerable<string> GetListValues(string currentCellKeys, string propertyName)
                    {
                        var keys = currentCellKeys.Split(',');
                        foreach (var key in keys)
                        {
                            string displayValue = null;
                            cellOptions.FirstOrDefault(x => x.ColumnName == propertyName)
                                  ?.KeyValues?.TryGetValue(key.Trim(), out displayValue); // Look up display value for each key
                            yield return displayValue ?? key.Trim(); // Return display value or original key if not found
                        }
                    }

                    // Populate data rows
                    for (int i = 0; i < list.Count; i++)
                    {
                        for (int j = 0; j < propertyInfo.Count; j++)
                        {
                            object cellValue;
                            // Format DateTime values
                            if (dateArr != null && dateArr.Contains(propertyInfo[j].Name))
                            {
                                object value = propertyInfo[j].GetValue(list[i]);
                                cellValue = value == null ? "" : ((DateTime)value).ToString("yyyy-MM-dd HH:mm:ss").Replace(" 00:00:00", ""); // Remove time if it's midnight
                            }
                            else
                            {
                                cellValue = propertyInfo[j].GetValue(list[i]);
                            }
                            // Convert dictionary keys to display values for export
                            if (cellValue != null && dicNoKeys.Exists(x => x.ColumnName == propertyInfo[j].Name))
                            {
                                if (selectListCols.Contains(propertyInfo[j].Name)) // Handle multi-select
                                {
                                    cellValue = string.Join(",", GetListValues(cellValue.ToString(), propertyInfo[j].Name));
                                }
                                else // Handle single-select
                                {
                                    string result = null;
                                    cellOptions.FirstOrDefault(x => x.ColumnName == propertyInfo[j].Name)
                                        ?.KeyValues?.TryGetValue(cellValue.ToString(), out result);
                                    cellValue = result ?? cellValue; // Use display value or original key if not found
                                }
                            }
                            worksheet.Cells[i + 2, j + 1].Value = cellValue; // Data starts at row 2
                        }
                    }
                    package.SaveAs(new FileInfo(fullPath));
                }
                return fullPath;
            }
            catch (Exception ex)
            {
                VOL.Core.Services.Logger.Error(VOL.Core.Enums.LogLevel.Error, VOL.Core.Enums.LogEvent.Exception, $"Error exporting List<{typeof(T).Name}> to Excel file {fileName}", null, ex);
                throw;
            }
        }

        // Overloads for ExportTemplate, simplifying calls to the main Export<T> method with template=true.
        /// <summary>Exports an Excel template for type T, including specified columns and excluding ignored columns.</summary>
        public static string ExportTemplate<T>(List<string> exportColumns, List<string> ignoreColumns, string savePath, string fileName) where T : class => Export<T>(null, exportColumns, ignoreColumns, savePath, fileName, true);
        /// <summary>Exports an Excel template for type T, using an expression to specify columns and excluding ignored columns.</summary>
        public static string ExportTemplate<T>(Expression<Func<T, object>> exportColumns, List<string> ignoreColumns, string savePath, string fileName) where T : class => Export<T>(null, exportColumns?.GetExpressionToArray(), ignoreColumns, savePath, fileName, true);
        /// <summary>Exports an Excel template for type T, excluding specified ignored columns.</summary>
        public static string ExportTemplate<T>(List<string> ignoreColumns, string savePath, string fileName) where T : class => Export<T>(null, null, ignoreColumns, savePath, fileName, true);
        /// <summary>Exports data or a template for type T, using an expression to specify columns to ignore.</summary>
        public static string Export<T>(List<T> list, Expression<Func<T, object>> ignore, string savePath, string fileName, bool template = false) where T : class => Export(list, null, ignore?.GetExpressionProperty(), savePath, fileName, template);


        /// <summary>
        /// Gets column information for Excel export/import, including display names, widths, and dictionary data sources.
        /// This method queries <see cref="Sys_TableColumn"/> for metadata.
        /// </summary>
        /// <param name="tableName">The entity/table name for which to retrieve column information.</param>
        /// <param name="template">If true, prepares options for template generation (may affect dictionary loading strategy, though not explicitly different here yet).</param>
        /// <param name="filterKeyValue">If true (default), filters dictionary items where key and value are the same (often used to hide redundant entries).</param>
        /// <param name="columns">Optional array of specific column (property) names to retrieve. If null or empty, retrieves columns marked for display (IsDisplay == 1).</param>
        /// <returns>A list of <see cref="CellOptions"/> for the specified columns.</returns>
        private static List<CellOptions> GetExportColumnInfo(string tableName, bool template = false, bool filterKeyValue = true, string[] columns = null)
        {
            // Query Sys_TableColumn for metadata related to the given tableName
            var query = DBServerProvider.DbContext.Set<Sys_TableColumn>().Where(x => x.TableName.ToLower() == tableName.ToLower());
            if (columns != null && columns.Length > 0) // If specific columns are requested
            {
                query = query.Where(x => columns.Contains(x.ColumnName));
            }
            else // Default: get columns marked for display
            {
                query = query.Where(x => x.IsDisplay == 1);
            }
            // Project to CellOptions
            List<CellOptions> cellOptions = query.OrderByDescending(x => x.OrderNo).Select(c => new CellOptions()
            {
                ColumnName = c.ColumnName, ColumnCNName = c.ColumnCnName, DropNo = c.DropNo,
                Requierd = c.IsNull <= 0, ColumnWidth = c.ColumnWidth ?? 90, EditType = c.EditType, SearchType = c.SearchType
            }).ToList();

            // If just generating a template definition, dictionary values might not be immediately needed here,
            // as EPPlus data validation lists are populated later. However, they are fetched for completeness.
            // if (template) return cellOptions;

            // Get distinct dictionary numbers (DropNo) for which to fetch items
            var dicNos = cellOptions.Where(x => !string.IsNullOrEmpty(x.DropNo)).Select(c => c.DropNo).Distinct();
            if (!dicNos.Any()) return cellOptions; // No dictionaries to fetch

            // Fetch dictionary items from DictionaryManager
            var dictionaries = DictionaryManager.GetDictionaries(dicNos);
            foreach (string dicNo in dicNos)
            {
                // Prepare KeyValues for each CellOption that uses this dicNo
                // Using OrdinalIgnoreCase for dictionary keys to handle potential case discrepancies if values come from various sources.
                Dictionary<string, string> keyValues = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                List<Sys_DictionaryList> dictionaryLists = dictionaries
                   .FirstOrDefault(x => x.DicNo == dicNo)?.Sys_DictionaryList;

                if (dictionaryLists == null || !dictionaryLists.Any()) continue; // Skip if no items for this dicNo

                foreach (var item in dictionaryLists)
                {
                    // Optional filter: if key and value are the same, some systems might want to hide them
                    if (filterKeyValue && item.DicName == item.DicValue && !string.IsNullOrEmpty(item.DicValue)) continue;

                    // Store mapping: typically, Excel shows DicName (Value), and internally we use DicValue (Key)
                    // For import, we map Excel display name back to internal key.
                    // For export, we map internal key to Excel display name.
                    // Here, KeyValues seems to store { DictionaryValue (from DB, often the Key/ID), DictionaryName (from DB, often the DisplayText) }
                    if (!keyValues.ContainsKey(item.DicValue))
                    {
                         keyValues.Add(item.DicValue, item.DicName);
                    }
                }
                // Assign the populated KeyValues to all CellOptions that use this dicNo
                foreach (CellOptions options in cellOptions.Where(x => x.DropNo == dicNo))
                {
                    options.KeyValues = keyValues;
                }
            }
            return cellOptions;
        }

        /// <summary>
        /// Exports a list of dictionaries to an Excel file. Each dictionary in the list represents a row,
        /// where dictionary keys are column headers and values are cell content.
        /// </summary>
        /// <param name="rows">List of dictionaries to export.</param>
        /// <param name="fileName">The name for the exported Excel file (e.g., "Report.xlsx").</param>
        /// <param name="path">Optional. The directory path to save the file.
        /// Defaults to "Download/ExcelExport/{CurrentDate}/". The path will be mapped to an absolute path.</param>
        /// <param name="onFillCell">Optional. An action to customize cell properties during export.
        /// Parameters: Worksheet, Row Index (0-based for header, 1+ for data), Column Index (0-based), Cell Value.</param>
        /// <param name="saveBefore">Optional. An action to perform on the worksheet (e.g., add protection, freeze panes) before saving.</param>
        /// <returns>The relative path (from application root if MapPath was involved) to the saved Excel file.</returns>
        /// <exception cref="Exception">Throws if an error occurs during Excel generation or saving.</exception>
        public static string ExportGeneralExcel(
         List<Dictionary<string, object>> rows,
         string fileName,
         string path = null,
         Action<ExcelWorksheet, int, int, object> onFillCell = null,
         Action<ExcelWorksheet> saveBefore = null)
        {
            // Delegate to the IDictionary<string, object> version for actual implementation
            return ExportGeneralExcel(rows.Select(item => item as IDictionary<string, object>).ToList(), fileName, path, onFillCell, saveBefore);
        }

        /// <summary>
        /// Exports a list of IDictionary objects to an Excel file. Each IDictionary represents a row,
        /// where dictionary keys are column headers and values are cell content. This is the core implementation.
        /// </summary>
        /// <param name="rows">List of IDictionary objects to export.</param>
        /// <param name="fileName">The name for the exported Excel file (e.g., "Report.xlsx"). A GUID will be prepended to ensure uniqueness.</param>
        /// <param name="path">Optional. The directory path to save the file.
        /// Defaults to "Download/ExcelExport/{CurrentDate}/". This path will be mapped to an absolute physical path.</param>
        /// <param name="onFillCell">Optional. An action to customize cell properties during export.
        /// Parameters: Worksheet, Row Index (0 for header, 1+ for data), Column Index (0-based), Cell Value.</param>
        /// <param name="saveBefore">Optional. An action to perform on the worksheet (e.g., add protection) before saving.</param>
        /// <returns>The relative path (from application root if MapPath was involved, combining input path and filename) to the saved Excel file.</returns>
        /// <exception cref="Exception">Throws if an error occurs during Excel generation or saving.</exception>
        public static string ExportGeneralExcel(
                List<IDictionary<string, object>> rows,
                string fileName,
                string path = null,
                Action<ExcelWorksheet, int, int, object> onFillCell = null,
                Action<ExcelWorksheet> saveBefore = null)
        {
            // Default path if not provided, including a date-based subfolder
            path = path ?? Path.Combine("Download","ExcelExport", DateTime.Now.ToString("yyyyMMdd"));
            string fullPath = path.MapPath(); // MapPath likely resolves to an absolute physical path
            fileName = Guid.NewGuid() + "_" + fileName; // Prepend GUID to filename for uniqueness
            if (!Directory.Exists(fullPath)) Directory.CreateDirectory(fullPath);

            try
            {
                using (ExcelPackage package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("sheet1");
                    // Populate header row if data exists
                    if (rows != null && rows.Any() && rows[0] != null && rows[0].Any())
                    {
                        int j = 0;
                        // Use keys from the first dictionary as headers
                        foreach (var headerKey in rows[0].Keys)
                        {
                            worksheet.Cells[1, j + 1].Value = headerKey;
                            worksheet.Row(1).Height = 20; // Set header row height
                            var style = worksheet.Cells[1, j + 1].Style;
                            style.Fill.PatternType = ExcelFillStyle.Solid;
                            style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                            style.VerticalAlignment = ExcelVerticalAlignment.Center;
                            style.Font.Bold = true;
                            style.Fill.BackgroundColor.SetColor(Color.FromArgb(216, 216, 216)); // Light gray background
                            style.Border.BorderAround(ExcelBorderStyle.Thin, Color.FromArgb(191, 191, 191)); // Thin border
                            onFillCell?.Invoke(worksheet, 0, j, headerKey); // Callback for header cell customization (row index 0 for header)
                            j++;
                        }
                    }

                    // Populate data rows
                    if (rows != null) {
                        for (int i = 0; i < rows.Count; i++) // Iterate through list of dictionaries (rows)
                        {
                            var rowData = rows[i];
                            if (rowData == null) continue; // Skip if a row dictionary is null
                            int j = 0;
                            foreach (var cellPair in rowData) // Iterate through key-value pairs in the dictionary (cells)
                            {
                                // This assumes column order is consistent with headers if headers were from rows[0].Keys.
                                // If column order can vary, map to header names.
                                worksheet.Cells[i + 2, j + 1].Value = cellPair.Value; // Data starts at row 2
                                onFillCell?.Invoke(worksheet, i + 1, j, cellPair.Value); // Callback for data cell customization (row index 1+ for data)
                                j++;
                            }
                        }
                    }

                    // Auto-fit columns for better readability if there's content
                    if (worksheet.Dimension != null)
                    {
                        worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();
                        // Add a little extra width after AutoFit, but cap it to avoid excessively wide columns.
                        for (var col = 1; col <= worksheet.Dimension.End.Column; col++)
                        {
                            double currentWidth = worksheet.Column(col).Width;
                            worksheet.Column(col).Width = Math.Min(currentWidth + 2, 80); // Cap width at 80 (example)
                        }
                    }

                    saveBefore?.Invoke(worksheet); // Callback for any actions needed before saving (e.g., sheet protection)
                    package.SaveAs(new FileInfo(Path.Combine(fullPath,fileName))); // Save the file
                }
                // Return the relative path (input path + filename)
                return Path.Combine(path, fileName);
            }
            catch (Exception ex)
            {
                VOL.Core.Services.Logger.Error(VOL.Core.Enums.LogLevel.Error, VOL.Core.Enums.LogEvent.Exception, $"Error in ExportGeneralExcel for file {fileName}", null, ex);
                throw; // Re-throw for higher-level error handling
            }
        }
    }

    /// <summary>
    /// Represents options and metadata for a cell or column during Excel export or import operations.
    /// This class is used to define how entity properties map to Excel columns, including display names,
    /// data types, formatting, and data validation (especially for dictionary-bound fields).
    /// </summary>
    public class CellOptions
    {
        /// <summary>Gets or sets the property name of the entity that corresponds to this Excel column.</summary>
        public string ColumnName { get; set; }
        /// <summary>Gets or sets the Chinese (or other language) display name for the column header in Excel.</summary>
        public string ColumnCNName { get; set; }
        /// <summary>Gets or sets the dictionary number (DropNo) if this column is bound to a data dictionary.
        /// This is used to populate dropdown lists in Excel templates or validate data during import.</summary>
        public string DropNo { get; set; }
        /// <summary>Gets or sets the desired column width for Excel export. The unit might be character width or another EPPlus unit.</summary>
        public int ColumnWidth { get; set; }
        /// <summary>Gets or sets a value indicating whether this column is required (cannot be null or empty during import).</summary>
        public bool Requierd { get; set; } // Typo: "Requierd" should be "Required"
        /// <summary>Gets or sets the 1-based index of this column as found in the Excel template file (used during import to map Excel columns to properties).</summary>
        public int Index { get; set; }
        /// <summary>Gets or sets the edit type (e.g., "select", "selectList", "checkbox", "date") for this column,
        /// often related to how it's displayed or edited in a UI, and can influence template generation or import validation.</summary>
        public string EditType { get; set; }
        /// <summary>Gets or sets the search type for this column when used in search forms, similar to <see cref="EditType"/>.</summary>
        public string SearchType { get; set; }
        /// <summary>Gets or sets the key-value pairs for dictionary-bound dropdowns.
        /// The Key is typically the internal/stored value (e.g., an ID), and the Value is the display name shown in Excel.
        /// For import, this map is used to convert display names back to keys. For export, keys are converted to display names.</summary>
        public Dictionary<string, string> KeyValues { get; set; }
    }
}
